use_frameworks!

def shared_pods
  pod 'SwiftLint'
  pod 'NestedCloudKitCodable', :path => '../'
end

target 'NestedCloudKitCodable_Example' do
  shared_pods
end

target 'NestedCloudKitCodableWatch Extension' do
  shared_pods
end

